arenas:
  # ------------------ 12 игроков ------------------
  arena12_1:
    world: "arena12_1"
    maxPlayers: 12
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [8, 65, 0]
      - [10, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]
      - [8, 65, 2]
      - [10, 65, 2]

  arena12_2:
    world: "arena12_2"
    maxPlayers: 12
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [8, 65, 0]
      - [10, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]
      - [8, 65, 2]
      - [10, 65, 2]

  arena12_3:
    world: "arena12_3"
    maxPlayers: 12
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [8, 65, 0]
      - [10, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]
      - [8, 65, 2]
      - [10, 65, 2]

  # ------------------ 8 игроков ------------------
  arena8_1:
    world: "arena8_1"
    maxPlayers: 8
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]

  arena8_2:
    world: "arena8_2"
    maxPlayers: 8
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]

  arena8_3:
    world: "arena8_3"
    maxPlayers: 8
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [4, 65, 0]
      - [6, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
      - [4, 65, 2]
      - [6, 65, 2]

  # ------------------ 4 игрока ------------------
  arena4_1:
    world: "arena4_1"
    maxPlayers: 4
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]

  arena4_2:
    world: "arena4_2"
    maxPlayers: 4
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]

  arena4_3:
    world: "arena4_3"
    maxPlayers: 4
    spawnPoints:
      - [0, 65, 0]
      - [2, 65, 0]
      - [0, 65, 2]
      - [2, 65, 2]
